#import "lib.typ": wiki

#show: wiki.with(
	title:[
	  Continued Fractions: Analytic Theory and Application
	]
)

== William B. Jones and W.J. Thron IBSN: 0201135108

#link("https://f005.backblazeb2.com/file/wwwmdf/Continued_Fractions-0201135108.pdf")[
  Jones, William B. 1980. Continued Fractions. Analytic Theory and Applications. Forew. By Felix E. Browder. IBSN: 0201135108
]

(The Study of Continued Fractions) began in its explicit form in the latter decades of the 16th century with a paper by Bombelli written when the concepts and notations of algebra were first being laid down in Italy and France. Such expressions play a natural role in connection with the iterated application of the Euclidean algorithm and some mathematical historians have claimed to have found similar usages in Hindu or even Greek mathematics. Infinite continued fractions were first considered by Lord Brouncker, first president of the Royal Society. The earliest continued fractions had whole numbers as their entries and were applied to the rational approximation of various algebraic numbers and of IT. The use of continued fractions as an important tool in number theory began with 17th century results of Schwenter, Huygens, and Wallis and came to maturity with the work of Euler in 1737 and the subsequent use of continued fractions as a number theoretic tool by Lagrange, Legendre, Gauss, Galois, and their successors. Continued fraction expan- sions involving functions of a complex variable rather than simply num- bers were introduced by Euler and became an important tool in the approximation of special classes of analytic functions in the work of Euler, Lambert, and Lagrange. A particularly influential direction of study was the expansions in continued fractions introduced by Gauss in 1813 for ratios of hypergeometric functions, one of the earliest contexts in which orthogonal polynomials made their appearance. (pp xv-xvi)

The central position of the study of continued fractions in the difice of classical 19th century analysis is attested to by the long list of major analysts who treated problems in this area, including names like Laplace, Legendre, Jacobi, Eisenstein, Heine, Laguerre, Riemann, Stieltjes, Tchebycheff, Frobenius, and Poincare. The conceptual consequences of these investigations were far-reaching, particularly in the work of Stieltjes where they led to such far-reaching developments as the study of the moment problem (with all its eventual impact on the development of twentieth-century functional analysis), the definition and study of the Stieltjes integral, the beginnings of the systematic study of convergence of sequences of holomorphic functions (the Stieltjes-Vitali theorem) and the application of the early machinery of spectral theory for self-adjoint operators in Hilbert space to the moment problem by Hilbert and his school. Asymptotic expansions seem to have found an early origin in the work of Poincare and Stieltjes on the use of continued fraction expansions in connection with divergent series. (pp xvi)

Beginning in the area of statistical mechanics and solid state physics (but with a rapid extension to other areas of theoretical physics), techniques elaborated by Frobenius and Pade in the late nine- teenth century to obtain expansions of analytic functions in the complex plane in terms of rational functions given as approximants of continued fractions, have become a major computational tool under the general name of Pade approximants. The large-scale nature of the resulting computa- tional enterprise has given a renewed impetus to the whole field of study, and in particular has made the present volume very timely (pp xvii)

Mathematics derives much of its vitality from the fact that it has several faces, each face having its own sharply distinguished features. One face, which might be called the dialectic face of mathematics, is the face of a scholar, or even of a philosopher. It is the face which tells us whether theorems are true or false, and whether mathematical objects with speci- fied properties do or do not exist. Dialectic mathematics is an intellectual game, played according to rules about which there is a high degree of consensus, and where progress can be measured sharply in terms of the generality of a result that has been achieved. (pp xix)

There is another, entirely different face of mathematics, which I like to call its algorithmic face. This is the face of an engineer. The algorithmic mathematician tells us how to construct the beautiful things of whose existence we are assured by the dialectic mathematician. The rules of the game of algorithmic mathematics, and in particular the significance at- tached to results in algorithmic mathematics, depend on the equipment that is available to carry out the required constructions. (pp xix)

Dialectic mathematics has experienced a continuous growth at least since the time of C. F. Gauss. Algorithmic mathematics, on the other hand, has stagnated from Euler's time until very recently, because no really new computing equipment came into existence; even the manually operated desk calculator did not significantly increase the speed of computation. It has been brought to light by H. H. Goldstine that Gauss in essence invented the fast-Fourier-transform algorithm. Nobody seems to have cared at the time because, whether fast or not, it was not really possible to meet the computational demands of the discrete Fourier transform except on an utterly trivial level. (pp xix)

All this has changed, of course, with the invention of the electronic computer. Accordingly, we have experienced a surge in the use of algorith- mic mathematics, especially in engineering and in applied science, which is without parallel in the history of mathematics. (pp xix)

The theory of continuedfractions may serve as an example of a branch of algorithmic mathematics which has bloomed in the time of Euler, but whose growth since then has been rather modest compared to typical areas of dialectic mathematics such as group theory or topology. To explore and to make use of the algorithmic potential of a continued fraction has become possible, on a large scale, only since, thanks to von Neumann, we have learned how to compute. (pp xix)

One of the main reasons why continued fractions are so useful in computation is that they often provide representations for transcendental functions that are much more generally valid than the classical representa- tion by, say, the power series. Thus, for instance, while the power series at z = 0 of a meromorphic function represents that function only up to the nearest pole, continued-fraction representations exist for certain meromor- phic functions (see Section 6.1) which represent that function everywhere in the complex plane except at the poles. Beautiful as these results are, they have, at the present, more the character of isolated gems than of concrete manifestations of an underlying general theory. It certainly would be desirable to see at least the beginnings of such a theory. (pp xxi)

A famous application of continued fractions occurs in control theory. There it is often necessary to decide whether a given polynomial with real coefficients is stable, i.e., whether all of its zeros have negative real parts. This question can be answered, in a finite number of steps and without computing the zeros (pp xxi)

Two recent developments from outside have had a strong influence on the direction of research in continued fractions and thus on the selection of and emphasis on topics for this book. They are the discovery of Pade tables as an important tool in applications in the physical sciences (about 70 or 80 years after they had been introduced by Frobenius and Pade), and the advent of high-speed digital computers. (pp xxiv)

We therefore considered it important to include a brief introduction to Pade tables and bring out the connection between Pade approximants and continued fractions. The main connection is that the entries of the Pade table can be realized as approximants of suitably chosen continued frac- tions. Questions of convergence of sequences of Pade approximants can thus in numerous instances be answered by means of known results on the convergence of continued fractions. (pp xxiv)

It was L. Euler (1707-1783), beginning in 1737, who gave a systematic development of continued fractions. In his work it became clear that continued fractions can be employed both in number theory and in analysis. In this book we shall be concerned almost exclusively with the analytic theory of continued fractions. (pp 2)
