#import "lib.typ": wiki

#show: wiki.with(
	title:[
		Magisteria Magna
	]
)

== Thomas Harriot

== 9783037190593

9783037190593: Thomas Harriot's doctrine of triangular numbers : the 'Magisteria magna' European Mathematical Society, Heritage of European mathematics, 2009 Janet Beery; Jacqueline A Stedall; European Mathematical Society https://f005.backblazeb2.com/file/wwwmdf/Thomas_Harriot_Triangle_Numbers-9783037190593.pdf

- Thomas Harriot’s ‘doctrine of triangular numbers’ is contained in a manuscript treatise of thirty-eight pages, which was never published but which has survived amongst the several hundred pages of mathematical work left behind by Harriot after his death in 1621. The full title, as Harriot wrote it on the cover sheet, is ‘De Numeris Triangularibus et inde De Progressionibus Arithmeticis Magisteria magna T. H.’, which may be translated as ‘Of triangular numbers and thence of arithmetic progressions, the great doctrine, [by] T[homas] H[arriot]’.(pg 3)

- The pages that follow contain several tables, numerical and algebraic, and a multitude of equations and formulae, but hardly a word of explanation (pg 3)

- The ‘Magisteria’ was the document in which Harriot, towards the end of his life, summarized the method he had devised and used some years earlier for interpolating tables by means of constant differences. Its story is of historical importance for at least three reasons. First, Harriot worked out his method in considerable generality, and expressed the relevant formulae in something very close to modern algebraic notation, but it has never been published and the extent of his achievement has not been fully recognized. Second, it is clear from this present study that the methods presented in the 'Magesteria' were subject of discussion and research amongst english mathematicians for a period of about sixty years from 1610 to 1670. As we show later, Torporley, Warner, Pell, Collins, and Mercator, all explored Harriot’s methods before or independently of Newton’s rediscovery of them in 1665. Apart from a few isolated examples, however, their work on this subject was unpublished and has remained to all intents and purposes invisible to later historians. A topic of enduring interest in early seventeenth-century English mathematical circles has therefore until now passed largely unnoticed. (pg 3-4)

- A third important feature of this story is that it demonstrates how new mathematical ideas were disseminated between small groups of friends, and later passed from one generation to another, without appearing in printed texts. Communication was primarily through verbal explanation and discussion, accompanied by a few key manuscripts that circulated from hand to hand and were borrowed, copied, and talked about, in some cases over periods of up to thirty years. Apart from Harriot and Briggs, the people who wrote, read, or thought about these methods were not outstanding or innovative mathematicians, but all of them worked at the subject seriously and were part of small and fluid mathematical communities that over the years contributed in a variety of ways to the vitality of mathematical studies in England. (pg 4)

- The earliest introduction to figurate numbers to circulate widely in western Europe was ‘De institutione arithmeticae’ of Boethius (c. 500 ad). Largely based on an earlier work, the ‘Arithmetike isagoge’ of [Nicomachus](../philosophers/Nicomachus-of-Gerasa) (c. 100 ad), Boethius’ text preserved some elementary Euclidean number theory, and in the later sections introduced figurate numbers: linear, triangular, square, pentagonal, hexagonal, and heptagonal, together with various kinds of pyramidal numbers, and even spherical numbers. 7 Boethius showed how each kind of number can be generated (beautiful coloured diagrams accompany many manuscript copies of his text), and he also gave examples of a few simple relationships, for example, that the sum of two consecutive triangular numbers is a square number. In fact he claimed through this and similar examples that the simple triangular numbers are the basis of all others. Harriot twice mentioned Boethius as a source of information on triangular numbers, 8 and it is possible that he had access to a manuscript copy of ‘De institutione’, but he also probably knew the detailed commentary on it published by Jacques Lefevre (pg 5)

+ #link("../mathematicians/thomas-harriot.html")[Thomas Harriot]

- A more contemporary treatise, in Boethian style, mentioned by Harriot at least four times,10 was Francisco Maurolico’s Arithmeticorum libri duo of 1575. Maurolico’s text opens with a section in which he offered several lists of figurate numbers followed by the instructions for generating them. For triangular numbers he gave two methods: adding successive numbers or ‘roots’ (per continuatam radicum accumulationem), or multiplying a ‘root’ plus one by half of itself (multiplicando aggregatum collateralis radicis et unitatis in dimidium multitudinis radicum). For pyramidals he suggested only the addition of consecutive triangular numbers.11 In the main part of his text three propositions relate specifically to triangular numbers: Proposition 11, that the sum of two consecutive triangular numbers is a square number; Proposition 54, that eight times a triangular number plus one is a square number; and Proposition 58, that the square of a triangular number is a sum of cubes. All three were demonstrated by Harriot algebraically.12 Harriot noted that Stevin’s commentary on Diophantus and Viète’s Variorum responsorum also contain the second proposition.13 (pg 6)

- The texts of Boethius and Maurolico go no further than offering lists of numbers and a few elementary relationships. Triangular numbers appear in a more practical context, however, in Michael Stifel’s Arithmetica integra (1544), with which Harriot was also familiar.14 Stifel recognized the role of the triangular numbers in the expansion of powers of a binomial, and therefore, conversely, their use in extracting roots (by an extension of the usual algorithm for square roots). Near the beginning of his treatment he offered some ‘progressions’ of polygonal numbers and displayed some small difference tables, observing, for instance, that the first differences between successive pyramidal numbers are triangular numbers, and that second differences are ‘laterals’.15 Towards the end he gave a table of triangular numbers with seventeen rows.16 (pg 6)

- The interpolation of trigonometric tables was clearly one possible use of Harriot’s difference method. (pg 15)

- Harriot also worked for many years on the calculation of meridional parts (the adjustments needed at each degree of latitude in order to calculate an accurate position on a constant compass bearing).36 His tables of meridional parts and also some of the preliminary tables show many difference calculations, sometimes as far as the fifth difference. (pg 15)

- As a check on this formula Harriot noted a rule given by Maurolico which states that a sum of cubes is the square of the corresponding triangular number.46 Harriot used the same method to derive formulae for sums of consecutive numbers, squares, and fourth powers, and clearly he could have extended it to higher powers if he had wanted to. Such formulae became crucial to the development of integration theory when they were rediscovered by Fermat and others a few years later (pg 20)

- Nathaniel Torporley, who shared and understood Harriot’s mathematical interests better than anyone, was educated at Oxford slightly after Harriot, from 1581. The date of their meeting and the subsequent course of their friendship is unknown, but a letter that Torporley wrote to Harriot on the eve of his first meeting with Viète, in or shortly after 1600, indicates that both he and Harriot were already familiar with Viète’s mathematics.48 Torporley then became an assistant to Viète, until the latter died in 1603, and in 1608 he became vicar of Salwarpe, in Shropshire. Thereafter he was probably in less regular contact with Harriot.(pg 20)
