editview:
	nvim view_plan.dot

renderview:
	dot -Tsvg view_plan.dot > view_plan.svg

seeview:
	chafa view_plan.svg

editviewmodel:
	nvim viewmodel_plan.dot

renderviewmodel:
	dot -Tsvg viewmodel_plan.dot > viewmodel_plan.svg

seeviewmodel:
	chafa viewmodel_plan.svg


